apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: elearning
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8007
      targetPort: 8007
  type: ClusterIP
