apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: elearning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: elearning/analytics-service:latest
          ports:
            - containerPort: 8007
          envFrom:
            - configMapRef:
                name: elearning-config
            - secretRef:
                name: elearning-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
